name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest

    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Integration tests
        run: npm run test:integration

      # Verify Google Cloud Access
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GOOGLE_PROJECT_ID }}
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}"

      - name: Deploy to Google Cloud Functions (Test)
        if: github.ref != 'refs/heads/main'
        uses: "google-github-actions/deploy-cloud-functions@v3"
        timeout-minutes: 10
        with:
          name: "oracleEngineTest"
          runtime: "nodejs22"
          entry_point: "oracleEngine"
          environment_variables: |-
            DISCORD_PUBLIC_KEY=${{ secrets.DISCORD_PUBLIC_KEY }}
          secrets: |-
            DISCORD_TOKEN=projects/381372803287/secrets/DISCORD_TOKEN/versions/1
            OPENAI_API_KEY=projects/381372803287/secrets/OPENAI_API_KEY/versions/1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: "read"
      id-token: "write"
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GOOGLE_PROJECT_ID }}
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}"

      - name: Deploy to Google Cloud Functions
        uses: "google-github-actions/deploy-cloud-functions@v3"
        timeout-minutes: 10
        with:
          name: "oracleEngine"
          runtime: "nodejs22"
          environment_variables: |-
            DISCORD_PUBLIC_KEY=${{ secrets.DISCORD_PUBLIC_KEY }}
          secrets: |-
            DISCORD_TOKEN=projects/381372803287/secrets/DISCORD_TOKEN/versions/1
            OPENAI_API_KEY=projects/381372803287/secrets/OPENAI_API_KEY/versions/1
