name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Integration tests
        run: npm run test:integration

      # Verify Google Cloud Access
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Deploy to Google Cloud Functions (Test)
        if: github.ref != 'refs/heads/main'
        uses: "google-github-actions/deploy-cloud-functions@v3"
        timeout-minutes: 10
        with:
          name: "oracleEngineTest"
          runtime: "nodejs22"
          entry_point: "oracleEngine"
          environment_variables: |-
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
            DISCORD_PUBLIC_KEY=${{ secrets.DISCORD_PUBLIC_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GOOGLE_PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Deploy to Google Cloud Functions
        uses: "google-github-actions/deploy-cloud-functions@v3"
        timeout-minutes: 10
        with:
          name: "oracleEngine"
          runtime: "nodejs22"
          environment_variables: |-
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
            DISCORD_PUBLIC_KEY=${{ secrets.DISCORD_PUBLIC_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
